### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Zarathustra98** [Xiangyu-Hu/SPHinXsys#125]
Dear all,
I'm installing this solver with Visual Studio Community 2017 and encountered two types of (MSB 3073 and LNK1181) errors when trying to build and install the project. It seems that I'm missing the ''structural_simulation_module.lib'' file or failing to link the lib file somehow. 
I put the errors into a txt file below.
[Error log.txt](https://github.com/Xiangyu-Hu/SPHinXsys/files/8828446/Error.log.txt)
Bests,
Jun Li

**Comment by Xiangyu-Hu** [comment]
Yes. There is such error for windows. It is because in thr cmakelist for building the structure simulation lib is only setup for Linux. This is done in a current developing branch and will be released soon. However, if you need to use this lib, you can slightly modify the cmake following those for 2d or 3d build.
