### ISSUE TITLE
Need help in creating user-defined case

### ISSUE THREAD

**Issue by Zarathustra98** [Xiangyu-Hu/SPHinXsys#131]
Dear all,
Is it possible to provide some tutorials on how to create user-defined cases? I found that we cannot simply add a new project to the solution file and some extra processes need to be done before we create a new test case. Currently I comment the unused test cases and write the code on these files and I wondered if there is a clever way to solve this issue.
Thanks

**Comment by Xiangyu-Hu** [comment]
There are two ways to use the library for your own problems.
One is to install the library to a destination folder and use it as a third part library.
The second and easiest way is creating new user examples within the project.

This can be done by simply copy a test example (with the entire folder, such as test_2d_dambreak) 
into the folder called user_examples. Please copy a 2D example if your own cases is 2D, 
a 3D example if your own case is 3D too. 

Then, you can modify the names of the folder and cpp file to creat a new case. 
After that, you can modify the cpp or header files for your own application. 
Finally, you rerun Cmake for the entire project so that your own case will be included.

**Comment by Zarathustra98** [comment]
I notice that there is a CmakeLists file for every example. Do I need to modify that file too?
