### ISSUE TITLE
Nonlinear wave interaction case in 3d takes too long time in CI

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#357]
The nonlinear wave interaction case in 3d takes too long time. It takes about 2500 seconds in CI.
@ncsalis Could it possible to shorten the time to about 1000 seconds?

**Comment by Xiangyu-Hu** [comment]
Probably, running for less physical time?

**Comment by ncsalis** [comment]
If we want to shorten the simulation time in CI, the modifications must include lower particle resolution, shorter channel and shorter physical time. I have done it, tomorrow I will check results and re-build regression since time sep changed.

If 1000 seconds in CI cannot be achieved with this new configuration I suggest to de-activate the case from running in CI.

**Comment by ncsalis** [comment]
With this configuration takes (circa) 1600s on linux, 2400s on windows and 1400s on macOS. 

It's better to deactivate the case for CI or remove it. In the following weeks I shall prepare a different configuration for testing purposes.

**Comment by Xiangyu-Hu** [comment]
OK. You can replace the 3d case with a new one. Thanks.

**Comment by ncsalis** [comment]
Modified case. Now it should take from 250 to 300 seconds in CI.

![nlwfsi_lq](https://github.com/Xiangyu-Hu/SPHinXsys/assets/56539341/40f49e9e-6faa-4b9a-8244-6a10b79ca327)

**Comment by Xiangyu-Hu** [comment]
Good. I think that it is good enough.

**Comment by Xiangyu-Hu** [comment]
We can replace the old one with this.

**Comment by ncsalis** [comment]
Is already substituted and running in #358. Is not as fast as I hoped, in linux takes circa 600s. If you need faster I have to think another different configuration.
