### ISSUE TITLE
Units of parameters?

### ISSUE THREAD

**Issue by RussellZhangYo** [Xiangyu-Hu/SPHinXsys#82]
Hi, I think the units of the reference value of parameters are different for different cases.

How can I know the units of parameters in each case.

For example, in the case "test_2d_dambreak", what are the units of liquid column height 'LH' and end time "End_Time".  In the case "test_2d_wetting_effects", what are the units of  tank height "DH", reference density "rho0_f", water viscosity "mu_f", surface tension "tension_force" and  end time "End_Time".

**Comment by Xiangyu-Hu** [comment]
Yes. The code itself is independent of units, therefore, 
one need to define all parameters and their unit in the application.
Therefore, each test case has their own unit system.

**Comment by RussellZhangYo** [comment]
> Yes. The code itself is independent of units, therefore, one need to define all parameters and their unit in the application. Therefore, each test case has their own unit system.

Thank you very much, Prof. Hu.

I would like to ask how can I know the pre-defined unit system of each case in the SPHinXsys.

**Comment by Xiangyu-Hu** [comment]
At the begin of the case source or its header, the global geometry and material parameters are given in arbitrary units. 
One can determine the exactly used units by comparing them with known values in standard units. 
For example, in the dam-break case, you know that the gravity is 9.8 m/s2 and water density 1000 kg/m3, then the units system is defined if you also know the geometry of the water tank.
However, the exact  units are actually not important in any of the cases
because the physics are only dependent on the non-dimensional numbers 
(the relative ratio between those parameters and the units are canceled).

**Comment by RussellZhangYo** [comment]
> At the begin of the case source or its header, the global geometry and material parameters are given in arbitrary units. One can determine the exactly used units by comparing them with known values in standard units. For example, in the dam-break case, you know that the gravity is 9.8 m/s2 and water density 1000 kg/m3, then the units system is defined if you also know the geometry of the water tank. However, the exact units are actually not important in any of the cases because the physics are only dependent on the non-dimensional numbers (the relative ratio between those parameters and the units are canceled).

Many thanks for your explanation, Prof, Hu.
